//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stratego.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stratego.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;map rows=&quot;10&quot; columns=&quot;10&quot;&gt;
        ///  &lt;player number=&quot;0&quot; color=&quot;green&quot;/&gt;
        ///  &lt;player number=&quot;1&quot; color=&quot;red&quot;/&gt;
        ///  &lt;row i=&quot;0&quot;&gt;
        ///    &lt;cell j=&quot;0&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;1&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;2&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;3&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;4&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;5&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;6&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;7&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;8&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;9&quot; acce [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string pattern2 {
            get {
                return ResourceManager.GetString("pattern2", resourceCulture);
            }
        }
    }
}
