//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stratego.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stratego.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hide {
            get {
                object obj = ResourceManager.GetObject("hide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;map rows=&quot;10&quot; columns=&quot;10&quot;&gt;
        ///  &lt;player number=&quot;0&quot; color=&quot;green&quot;/&gt;
        ///  &lt;player number=&quot;1&quot; color=&quot;red&quot;/&gt;
        ///  &lt;row i=&quot;0&quot; owner=&quot;1&quot;&gt;
        ///    &lt;cell j=&quot;0&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;1&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;2&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;3&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;4&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;5&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;6&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;7&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell j=&quot;8&quot; accessible=&quot;true&quot;/&gt;
        ///    &lt;cell  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pattern2 {
            get {
                return ResourceManager.GetString("pattern2", resourceCulture);
            }
        }
    }
}
